### ISSUE TITLE
for next few days ..

### ISSUE THREAD

**Issue by arec2053** [desaiyang/trng#12]
1. first review self-learning-1.pptx
2. follow instructions and install postgresql database and bitnami on your computer
3. create an account with github and connect with desaiyang/trng repository.
4. we will be using github to track your training progress
5. go thru dyncould-with-narration-TRNG.ppsx.
 6. from your computer go to dyncould.com and click on web class training log in.
6. enter tester1@tester1.com as user name
7. password: ask guna
8. enter wed class notes, todos, and upload a test file.
9. enter all these in github and mark [success]
10. notify your instructor.

**Comment by desaiyang** [comment]
closing .. for review

gd
12/28
